apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: chatbot-sample-app-aug14
  janus-idp.io/tekton: chatbot-sample-app-aug14
  backstage.io/kubernetes-id: chatbot-sample-app-aug14
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: chatbot-sample-app-aug14
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
- rhoai/